services:
  frontend:
    container_name: aka-frontend
    image: ${REGISTRY}/frontend:latest
    restart: always
    networks:
      - network
    profiles:
      - frontend
      - deploy
  database:
    container_name: aka-database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: aka-cloudbeaver
    restart: always
    depends_on:
      - database
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - network

  backend:
    container_name: aka-backend
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASS}@database/${PG_DB}
      CORS__ORIGIN: ${CORS_ORIGIN}
    image: ${REGISTRY}/backend:latest
    restart: always
    depends_on:
      - database
    networks:
      - network
    profiles:
      - backend
      - deploy

  cloudflare-tunnel:
    container_name: aka-cloudflare
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - network

networks:
  network:
    name: aka-network
    external: true
