services:
  frontend:
    container_name: aka-frontend
    image: ${REGISTRY}/frontend:latest
    restart: always
    networks:
      - network
    profiles:
      - frontend
      - deploy

  database:
    container_name: aka-database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - database:/var/lib/postgresql
    networks:
      - network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: aka-cloudbeaver
    restart: always
    depends_on:
      - database
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - network

  valkey:
    container_name: aka-valkey
    image: bitnami/valkey:latest
    environment:
      - VALKEY_PASSWORD=${REDIS_PASSWORD}
    networks:
      - network

  backend:
    container_name: aka-backend
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASS}@database/${PG_DB}
      FRONTEND_URL: ${FRONTEND_URL}
      REDIS_URL: ${REDIS_URL}
      CORS__ORIGIN: ${CORS_ORIGIN}
      BCRYPT__COST: ${BCRYPT_COST}
      BCRYPT__SALT: ${BCRYPT_SALT}
      JWT__SECRET: ${JWT_SECRET}
      JWT__REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      OAUTH2__GOOGLE__CLIENT_ID: ${GOOGLE_CLIENT_ID}
      OAUTH2__GOOGLE__CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OAUTH2__GOOGLE__REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      OAUTH2__GOOGLE__ISSUER_URL: "https://accounts.google.com"
      OAUTH2__GOOGLE__SCOPES: "email,profile"

      OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo:4317"
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "aka-backend"
      OTEL_TRACES_SAMPLER: "always_on"
    image: ${REGISTRY}/backend:latest
    restart: always
    depends_on:
      - database
    networks:
      - network
    profiles:
      - backend
      - deploy

  cloudflare-tunnel:
    container_name: aka-cloudflare
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - network

networks:
  network:
    name: aka-network
    external: true

volumes:
  database:
    name: aka-database
    external: true
  cloudbeaver:
    name: aka-cloudbeaver
    external: true
  elasticsearch:
    name: aka-elasticsearch
    external: true
