receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  resourcedetection:
    detectors: ["system"]

exporters:
  logging:
    loglevel: debug

  elasticsearch/trace:
    endpoints: ["http://elasticsearch:9200"]
    tls:
      insecure_skip_verify: true

  elasticsearch/logs:
    endpoints: ["http://elasticsearch:9200"]
    tls:
      insecure_skip_verify: true
    mapping:
      mode: ecs

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [elasticsearch/trace]

    logs:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [elasticsearch/logs, logging]
