[package]
name = "broadcast"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
futures = "0.3.31"
lapin = "3.7.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
