[package]
name = "json-web-token"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
jsonwebtoken = "10.0.0"
uuid = { version = "1.18.1", features = ["v4", "fast-rng"] }
