on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
      API_URL: ${{ secrets.API_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker compose -f compose.build.yaml --profile frontend build

      - name: Push image
        run: docker compose -f compose.build.yaml --profile frontend push

  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build image
        run: docker compose -f compose.build.yaml --profile backend build

      - name: Push image
        run: docker compose -f compose.build.yaml --profile backend push

  deploy:
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
      API_URL: ${{ secrets.API_URL }}
      CLOUDFLARE_TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASS: ${{ secrets.PG_PASS }}
      PG_DB: ${{ secrets.PG_DB }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
      SHA256_SECRET: ${{ secrets.SHA256_SECRET }}
      BCRYPT_COST: ${{ secrets.BCRYPT_COST }}
      BCRYPT_SALT: ${{ secrets.BCRYPT_SALT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URL: ${{ secrets.GOOGLE_REDIRECT_URL }}
      ELASTICSEARCH_USERNAME: ${{ secrets.ELASTICSEARCH_USERNAME }}
      ELASTICSEARCH_PASSWORD: ${{ secrets.ELASTICSEARCH_PASSWORD }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean container and image
        run: docker compose -f compose.yaml -p aka-space --profile deploy down -v

      - name: Deploy
        run: docker compose -f compose.yaml -p aka-space --profile deploy up -d --pull always
